### ISSUE TITLE
Tailwind CSS 2.0

### ISSUE THREAD

**Issue by rastreus** [albertwoo/FablePlayground#1]
Tailwind 2.0 was initially released yesterday with the following blog post ([link](https://blog.tailwindcss.com/tailwindcss-v2)).

Tailwind 2.0 is [incompatible with IE11](https://blog.tailwindcss.com/tailwindcss-v2#incompatibility-with-ie11):

> We've decided to unburden ourselves with caring about IE11 at all, which has allowed us to fully embrace CSS custom properties for all sorts of crazy stuff and is what makes things like the new ring utilities even possible.
> 
> Dropping IE11 support means smaller builds even when using PurgeCSS, because we don't have to ship any CSS variable fallbacks which adds up more than you'd expect.
> 
> Cheers to Bootstrap for having the cojones to do this first — I don't think we would have been so bold if they hadn't decided to pave the way.
> 
> The good news is that if you need to support IE11, you can always use Tailwind CSS v1.9 which is still an amazingly productive framework.

Do you plan to upgrade this template to Tailwind 2.0? I noticed you have ```> 0.25%, ie 11``` in your .browserslistrc file.

**Comment by albertwoo** [comment]
Wow, @rastreus you are very careful. Maybe I should drop ie 11 and if you or other people want to use ie11 then you can just change the config. Thanks:)
